name: Generate changelog
on:
  workflow_dispatch:
  # Defining workflow_call means that this workflow can be called from
  # your main workflow job
  workflow_call:
    # dist exposes the plan from the plan step, as a JSON string,
    # to your job if it needs it

permissions:
  contents: write

jobs:
  CHANGELOG:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: taiki-e/install-action@3522286d40783523f9c7880e33f785905b4c20d0 # v2.66.1
        with:
          tool: git-cliff

      - name: Generate changelog
        id: changelog
        run: git cliff -o -v
