name: test
permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  docker-test:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build
        run: docker build .
  test-with-httpyac:
    if: false
    runs-on: ubuntu-latest
    name: test with httpyac
    env:
      PORT: 1234
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2

      - name: Install netcat
        run: |
          if ! command -v nc &> /dev/null; then
            apt-get update && apt-get install -y netcat-openbsd
          fi

      - run: cargo b
      - run: echo "PORT=${{ env.PORT }}" > .env
      - run: cargo run  -- port ${{ env.PORT }} &

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            if nc -z localhost ${{ env.PORT }}; then
              echo "Server is up!"
              break
            else
              echo "Waiting for server..."
              sleep 1
            fi
          done

      - name: test
        id: test
        run: npx httpyac send test/test.http -a -e ./.env

      - run: rm ./.env

  cargo-test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          cache-all-crates: true

      # actions-rust-lang/setup-rust-toolchain is Caching for Rust tools and build artifacts is enabled.

      - uses: taiki-e/install-action@650c5ca14212efbbf3e580844b04bdccf68dac31 # v2.67.18
        with:
          tool: cargo-make

      - run: cargo make cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/nextest/ci/junit.xml
          report_type: test_results
